language: php
before_install:
    - if [[ "$(php --version | grep -cim1 xdebug)" -ge 1 ]]; then phpenv config-rm xdebug.ini; fi
git:
    depth: 5
install:
    - composer install
    - cp config/yapeal-example.yaml config/yapeal.yaml
matrix:
    allow_failures:
        - php:7.1
php:
    - 7.0
    - 7.1
script:
    - phpdbg -qrr -f vendor/dragonrun1/phpspec/bin/phpspec --no-interaction --config=phpspec_coverage.yml run
after_success:
    - travis_retry php vendor/bin/coveralls -v
