language: php
before_script:
  - phpenv config-rm xdebug.ini
git:
  depth: 5
install:
#  - composer selfupdate
  - composer install
  - cp config/yapeal-example.yaml config/yapeal.yaml
matrix:
  allow_failures:
    - php:7.1
 #   - php: 5.6
 #   - php: 5.5
 #   - php: hhvm
php:
  - 7.1
  - 7.0
#  - 5.6
#  - 5.5
#  - hhvm

script:
#    - mkdir -p build
    - phpdbg -qrr -f vendor\dragonrun1\phpspec\bin\phpspec --config=phpspec_coverage.yml run
#    - phpunit --coverage-clover build/logs/clover.xml

after_script:
    - travis_retry php vendor/bin/coveralls -v
