language: php
before_install:
  - if `php --version | grep -qi xdebug`; then phpenv config-rm xdebug.ini; fi
#  - if [[ $TRAVIS_PHP_VERSION != 7.1 ]]; then phpenv config-rm xdebug.ini; fi
  - phpenv config-rm xdebug.ini
git:
  depth: 5
install:
#  - composer selfupdate
  - composer install
  - cp config/yapeal-example.yaml config/yapeal.yaml
matrix:
  allow_failures:
    - php:7.1
 #   - php: 5.6
 #   - php: 5.5
 #   - php: hhvm
php:
  - 7.1
  - 7.0
#  - 5.6
#  - 5.5
#  - hhvm

script:
#    - mkdir -p build
    - phpdbg -qrr -f vendor/dragonrun1/phpspec/bin/phpspec --config=phpspec_coverage.yml run
#    - phpunit --coverage-clover build/logs/clover.xml

after_success:
    - travis_retry php vendor/bin/coveralls -v
